<?php

namespace App\Http\Controllers;

use App\Mail\ClientEmail;
use App\Models\Client;
use Illuminate\Support\Facades\Mail;

class EmailController extends Controller
{
    public function sendEmail()
    {
        $search = '@';
        $clients = Client::whereNotNull('email1')->get();
        foreach ($clients as $client) {
            $receiverEmailAddress[] = $client->getAttribute('email1');
        }
        $mailAddress = 'noreply@mobilgroup.az';
        $template = 'email';

        $emails = ['agalandarov@bna.az',
            'narginltd@gmail.com',
            'sales@asmetal.az',
            'a.zeynalov@166.az',
            'rajab.feyzullayev@toyota-absheron.az',
            'rajab.feyzullayev@groupmotors.az',
            'accounts@citco.az',
            'a.bahruz@hayatgroup.az',
            'office@fsca.az',
            'ruslanfarajov@uygunlar.com',
            'director@chery.az',
            'ruslanmillennium@gmail.com',
            'b.aliyev@mobilbroker.az',
            'info@mobex.az',
            'royal.z@astexnika.com',
            'contabilita.baku@esteri.it',
            'info@baroquestyle.az',
            'm.bagirov@bakusteel.com',
            'samir.farzaliyev@gilan-knauf.az',
            'murad_abdullayev_91@refmotors.az',
            'denizzhasanova@gmail.com',
            'gnl.baku@mail.ru',
            'a.nurlan@agsuaqropark.az',
            'e.rahimov@simplex.az',
            'ekoproductsaz@gmail.com',
            'alizadenatavan@yandex.ru',
            'svetlana.80.gr@gmail.com',
            'aydinallahverdiyev719@gmail.com',
            'almaz.novruzova@chevrolet-auto.az',
            'f-aydinoglu@mail.ru',
            'info@faridoptic.az',
            'saleh@azmetkim.az',
            'info@ozsut.az',
            'oksana.osmanova@aemgroup.az',
            'info@azintech.az',
            'orkhan_a@icloud.com',
            'afi.hasanov@list.ru',
            's.emin@technologies.az',
            'aygun.ilchin.i@gmail.com',
            'nabi.ismailov@ferrari-baku.com',
            'mahmud@demiragac.net',
            'qafarzade2014@gmail.com',
            'procurement@tuna.az',
            'emin@fleetstock.info',
            'tunar20082008@gmail.com',
            'y.seferov82@gmail.com',
            'muradagro@yandex.ru',
            'faig@brainlab.az',
            'info@buludtelecom.com',
            'esmer@a-classs.com',
            'Ruslan.Sultanov@greentech.az',
            'namiq.novruznt@gmail.com',
            'kadymov.emin@yandex.com',
            'rasul.nagiyev.2015@mail.ru',
            'azavto@mail.ru',
            'info@integras.az',
            'yaqub022@gmail.com',
            'Khalilova.Masma@bcg.com',
            'reservation@aznur.az',
            'zaka.gubadov@gmail.com',
            'i.mubarizoglu@gmail.com',
            'ramal_ahmedov@list.ru',
            'togrul.ismayil1@gmail.com',
            'm.mahsulov@hotmail.com',
            'r.a557@mail.ru',
            'ceo@gtexnology.com',
            'shakoturqay@gmail.com',
            'mirzalievaaisun@gmail.com',
            'bakhtizina@gmail.com',
            'customer1400@gmail.com',
            'office@richsport.az',
            'faikabdullayev@icloud.com',
            'GASANOVSABUHI@MAIL.RU',
            'info@jetour.az',
            'rekber@inbox.ru',
            'n.karimli@mobilbroker.az',
            'info@synergia-pharma.com',
            'procurement02@fsca.az',
            'info@mycar.az',
            'axundov.76@mail.ru',
            'office@sakur.az',
            'info@skyzonebaku.com',
            'info@ecobox.az',
            'nazarevich-e@mail.ru',
            'nadir.novruzov@gmail.com',
            'emin_28@mail.ru',
            'habibov.nadir81@gmail.com',
            'konstromat@sement.az',
            'kamilaliyev585@gmail.com',
            'anaraylant@gmail.com',
            'asifalizadeh88@gmail.com',
            'Farid.bagirov@aviongroup.az',
            'sq.konsaltinq@mail.ru',
            'procurement@caspianindustry.com',
            'info@aada.az',
            'customer1400gb@gmail.com',
            'baku.rifah@bk.ru',
            'info@auto.az',
            'necefov.2000@gmail.com',
            'f.abuzeroglu@mail.ru',
            'Elchin.tagiyev85@gmail.com',
            'aykhan.gulmammadov@gmail.com',
            'r.rahimov@mobilbroker.az',
            'ZUTECH030@gmail.com',
            'orxan93_quliyev@mail.ru',
            'Shahin.Gasimov@socardalgidj.az',
            'nesirnemetov@gmail.com',
            'akhalilli@proxima.az',
            'humaartroom@gmail.com',
            'eliyevrafael70@gmail.com',
            'mamta@bk.ru',
            's.novruzi@gmail.com',
            'sham-a@mail.ru',
            'mubariz.memmedov1990@gmail.com',
            'krzayeva@aris.az',
            'ilkin.khalili@gilan-knauf.az',
            'benenyarly.R@grb.kz',
            'Xazarauto@gmail.com',
            'office@mbgro.az',
            'xbabayev4466@gmail.com',
            'elnur.novruz@rotantefood.com',
            'allahverdiyeva.vd@azermash.az',
            'mammadov.f@officepro.az',
            'ramil8545@mail.ru',
            'ceferli1986@mail.ru',
            'e.haciyev95@mail.ru',
            'huseyin_memmedov91@bk.ru',
            'elnursa000@gmail.com',
            'info@yesilsaglik.az',
            'kanan@overmetal.az',
            'rbabayev13@gmail.com',
            'Agababa.dadashov@gmail.com',
            'faxri.huseyn@gmail.com',
            'info@parrotias.com',
            'info@tuib.az',
            'İnfo@ahik.org',
            'hresidov@yahoo.com',
            'nargiz.hajiyeva@noytech.com'
        ];

        Mail::to($emails)->send(new ClientEmail($mailAddress, $template));

        if (Mail::failures() != 0) {
            return "Email has been sent successfully.";
        }
        return "Oops! There was some error sending the email.";
    }
}